spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/v1/users/**
          filters:
            - StripPrefix=1

        - id: course-service
          uri: lb://course-service
          predicates:
            - Path=/api/v1/courses/**
          filters:
            - StripPrefix=1

        - id: user-service-v2
          uri: lb://user-service
          predicates:
            - Path=/api/v2/users/**
          filters:
            - StripPrefix=1

      default-filters:
        - name: RequestRateLimiter
          args:
            redis-rate-limiter.replenishRate: 10
            redis-rate-limiter.burstCapacity: 20

  redis:
    host: localhost
    port: 6379

server:
  port: 8080
